---
title: "Class_notes_10.23.18"
author: "Wendel Raymond"
date: "October 23, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Relational databases
Originaly created as a way to efficiently store large amounts of data. There are ways in R to access these databases.

## Methods
1) DBI ('DBI')
2) dplyr ('dplyr', 'dbplyr')
3) R Notebooks

any of these approaches you must connect to an external database

This opens a connection to a database
```{r, eval=FALSE}
con <- dbConnect(odbc::odbc(), dsn = "Source Name")
```

You can use dplyr syntax! With the connection as the first input to the chunck.

RNotebooks can allow for SQL directly as a differnet code chunk.

Can access MS Access via R too.

# Some notes on multivariate analysis
PERMANOVA! `adonis()` and `adonis2()`

## Steps in Analysis
1) Transformations and standardizations
  + transformations changes the shape of the distribution
  + strandardizations do not change the shape but scales the values to some level
  + transformation to achive normality is NOT necessary for many/all multivariate analyses. It just depends on hte situation.
  + Standarizations are almost alwayse a good idea
2) Compute pairwise dissimilarities using an *appropriate* measure
  + for sp composition data bary-curtis dissimilarity is the most appropriate becasue it can handle zeros
  + euclidean is highly affected by zeros. Use if are reasonably normal
  + lost of other distance measures
3) Ordination to visualize differences. Like PCA or NMDS. 
4) Interpret the ordination in terms of the data, e.g. species composition, sites, environmental data.
5) Relate the ordination to environmental variables
  + envifit()
  + Mantel test `bioenv()` in `vegan`
  + correlate envi variables to biological variables. Could do with different subset of environmental variables
6) PERMANOVA
  + generalizes multivariate AN(C)OVA for non-normal responses. Can use *any* distance measure to partition within and between group dispersion
  + with n-diemnsional data you compute the mean distances from the centroid rather than the mean like in a simple ANOVA setting. Test-stat is wilks lambda for MANOVA (multivariate normal)
  + Non-normal data don't really have centroids, so we use the pairwise distances between all samples, which is the same as the sum of squared distances from the centroid (Huygens theorem). Hurray!
  + PERMANOVA implements this! Thats why its a pseudo-F. Randomization to obtain dist. of p-F under null hypothesis. 
  + one should test for homoskedasisity `betadisper()` in `R`